name: 'CalVer tag'
description: 'Tag a commit with a CalVer version number in the format [YYYY.MM.DD-MICRO]'
author: 'Digital Udvikling'
branding:
  icon: tag
  color: blue
inputs:
  github_token:
    required: true
    description: 'GitHub token with repo write scope'
  prefix-tag:
    required: false
    description: 'Prefix to add to the git tag (not included in output)'
outputs:
  tag:
    description: 'The generated tag'
runs:
  using: 'node20'
  main: 'dist/index.js'
